[language-server.pyright-langserver]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright-langserver.config.analysis]
autoSearchPaths = true
diagnosticMode = "workspace"
useLibraryCodeForTypes = true

[language-server.rustup]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[language-server.cl-lsp]
command = "~/.roswell/bin/cl-lsp"
args = [ "stdio" ]

[[language]]
name = "python"
roots = ["pyrightconfig.json", "pyproject.toml", "."]
file-types = ["py"]
auto-format = false
formatter = { command = "black", args = ["--quiet", "-"] }
diagnostic-severity = "Hint"
language-servers = [ { name = "pyright-langserver"} ]

[[language]]
name = "rust"
language-servers = [ { name = "rustup"} ]

[[language]]
name = "common-lisp"
language-servers = [ { name = "cl-lsp"} ]

[[language]]
name = "clojure"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[[language]]
name = "scheme"
file-types = ["ss", "scm"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[[language]]
name = "emacs-lisp"
scope = "source.el"
roots = []
file-types = ["el"]
shebangs = []
comment-token = ";;"
indent = { tab-width = 2, unit = "  " }
grammar = "scheme"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
